version: '3.7'

services:
  
  vsftpd:
    build: 
      context: ./vsftpd-centos-8
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
        FTP_USER: 'user'
        FTP_PASS: 'user'
        ANONYMOUS_ACCESS: '*Boolean*'
        LOG_STDOUT: 'true'
        CUSTOM_PASSIVE_ADDRESS: 'localhost'
    volumes:
      - ./vsftpd-centos-8-vol/home:/home/vsftpd
      - ./vsftpd-centos-8-vol/logs:/var/log/vsftpd
    ports:
      - "0.0.0.0:20:20"
      - "0.0.0.0:21:21"
      - "21100-21110:21100-21110"


